// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: proto.proto

package proto

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// PeerToPeerClient is the client API for PeerToPeer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeerToPeerClient interface {
}

type peerToPeerClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerToPeerClient(cc grpc.ClientConnInterface) PeerToPeerClient {
	return &peerToPeerClient{cc}
}

// PeerToPeerServer is the server API for PeerToPeer service.
// All implementations must embed UnimplementedPeerToPeerServer
// for forward compatibility
type PeerToPeerServer interface {
	mustEmbedUnimplementedPeerToPeerServer()
}

// UnimplementedPeerToPeerServer must be embedded to have forward compatible implementations.
type UnimplementedPeerToPeerServer struct {
}

func (UnimplementedPeerToPeerServer) mustEmbedUnimplementedPeerToPeerServer() {}

// UnsafePeerToPeerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerToPeerServer will
// result in compilation errors.
type UnsafePeerToPeerServer interface {
	mustEmbedUnimplementedPeerToPeerServer()
}

func RegisterPeerToPeerServer(s grpc.ServiceRegistrar, srv PeerToPeerServer) {
	s.RegisterService(&PeerToPeer_ServiceDesc, srv)
}

// PeerToPeer_ServiceDesc is the grpc.ServiceDesc for PeerToPeer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerToPeer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PeerToPeer",
	HandlerType: (*PeerToPeerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto.proto",
}
