// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: proto/template.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Chittychat_SendChatMessage_FullMethodName   = "/proto.Chittychat/SendChatMessage"
	Chittychat_HandleNewClient_FullMethodName   = "/proto.Chittychat/HandleNewClient"
	Chittychat_ChatStream_FullMethodName        = "/proto.Chittychat/ChatStream"
	Chittychat_HandleClientLeave_FullMethodName = "/proto.Chittychat/HandleClientLeave"
)

// ChittychatClient is the client API for Chittychat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChittychatClient interface {
	SendChatMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*Ack, error)
	HandleNewClient(ctx context.Context, in *JoinOrLeaveMessage, opts ...grpc.CallOption) (*GiveTimestampAndAck, error)
	ChatStream(ctx context.Context, opts ...grpc.CallOption) (Chittychat_ChatStreamClient, error)
	HandleClientLeave(ctx context.Context, in *JoinOrLeaveMessage, opts ...grpc.CallOption) (*GiveTimestampAndAck, error)
}

type chittychatClient struct {
	cc grpc.ClientConnInterface
}

func NewChittychatClient(cc grpc.ClientConnInterface) ChittychatClient {
	return &chittychatClient{cc}
}

func (c *chittychatClient) SendChatMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, Chittychat_SendChatMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chittychatClient) HandleNewClient(ctx context.Context, in *JoinOrLeaveMessage, opts ...grpc.CallOption) (*GiveTimestampAndAck, error) {
	out := new(GiveTimestampAndAck)
	err := c.cc.Invoke(ctx, Chittychat_HandleNewClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chittychatClient) ChatStream(ctx context.Context, opts ...grpc.CallOption) (Chittychat_ChatStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Chittychat_ServiceDesc.Streams[0], Chittychat_ChatStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chittychatChatStreamClient{stream}
	return x, nil
}

type Chittychat_ChatStreamClient interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type chittychatChatStreamClient struct {
	grpc.ClientStream
}

func (x *chittychatChatStreamClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chittychatChatStreamClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chittychatClient) HandleClientLeave(ctx context.Context, in *JoinOrLeaveMessage, opts ...grpc.CallOption) (*GiveTimestampAndAck, error) {
	out := new(GiveTimestampAndAck)
	err := c.cc.Invoke(ctx, Chittychat_HandleClientLeave_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChittychatServer is the server API for Chittychat service.
// All implementations must embed UnimplementedChittychatServer
// for forward compatibility
type ChittychatServer interface {
	SendChatMessage(context.Context, *ChatMessage) (*Ack, error)
	HandleNewClient(context.Context, *JoinOrLeaveMessage) (*GiveTimestampAndAck, error)
	ChatStream(Chittychat_ChatStreamServer) error
	HandleClientLeave(context.Context, *JoinOrLeaveMessage) (*GiveTimestampAndAck, error)
	mustEmbedUnimplementedChittychatServer()
}

// UnimplementedChittychatServer must be embedded to have forward compatible implementations.
type UnimplementedChittychatServer struct {
}

func (UnimplementedChittychatServer) SendChatMessage(context.Context, *ChatMessage) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendChatMessage not implemented")
}
func (UnimplementedChittychatServer) HandleNewClient(context.Context, *JoinOrLeaveMessage) (*GiveTimestampAndAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleNewClient not implemented")
}
func (UnimplementedChittychatServer) ChatStream(Chittychat_ChatStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedChittychatServer) HandleClientLeave(context.Context, *JoinOrLeaveMessage) (*GiveTimestampAndAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleClientLeave not implemented")
}
func (UnimplementedChittychatServer) mustEmbedUnimplementedChittychatServer() {}

// UnsafeChittychatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChittychatServer will
// result in compilation errors.
type UnsafeChittychatServer interface {
	mustEmbedUnimplementedChittychatServer()
}

func RegisterChittychatServer(s grpc.ServiceRegistrar, srv ChittychatServer) {
	s.RegisterService(&Chittychat_ServiceDesc, srv)
}

func _Chittychat_SendChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChittychatServer).SendChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chittychat_SendChatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChittychatServer).SendChatMessage(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chittychat_HandleNewClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinOrLeaveMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChittychatServer).HandleNewClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chittychat_HandleNewClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChittychatServer).HandleNewClient(ctx, req.(*JoinOrLeaveMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chittychat_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChittychatServer).ChatStream(&chittychatChatStreamServer{stream})
}

type Chittychat_ChatStreamServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type chittychatChatStreamServer struct {
	grpc.ServerStream
}

func (x *chittychatChatStreamServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chittychatChatStreamServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Chittychat_HandleClientLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinOrLeaveMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChittychatServer).HandleClientLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chittychat_HandleClientLeave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChittychatServer).HandleClientLeave(ctx, req.(*JoinOrLeaveMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Chittychat_ServiceDesc is the grpc.ServiceDesc for Chittychat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chittychat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Chittychat",
	HandlerType: (*ChittychatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendChatMessage",
			Handler:    _Chittychat_SendChatMessage_Handler,
		},
		{
			MethodName: "HandleNewClient",
			Handler:    _Chittychat_HandleNewClient_Handler,
		},
		{
			MethodName: "HandleClientLeave",
			Handler:    _Chittychat_HandleClientLeave_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _Chittychat_ChatStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/template.proto",
}
